// src/constants/icons.ts

export const FOOD_ICONS = [
  { icon: './apple.png', title: 'Apple' }, { icon: './avocado.png', title: 'Avocado' },
  { icon: './bacon.png', title: 'Bacon' }, { icon: './bagel.png', title: 'Bagel' },
  { icon: './baguette.png', title: 'Baguette' }, { icon: './banana.png', title: 'Banana' }, { icon: './red-beans.png', title: 'Beans' },
  { icon: './beer.png', title: 'Beer' }, { icon: './bell-pepper.png', title: 'Bell Pepper' },
  { icon: './blueberry.png', title: 'Blueberries' },
  { icon: './ribs.png', title: 'Ribs' }, { icon: './cereal.png', title: 'Cereal' }, { icon: './white-bread.png', title: 'Bread' },
  { icon: './broccoli.png', title: 'Broccoli' }, { icon: './bubble-tea.png', title: 'Bubble Tea / Boba' }, { icon: './cheeseburger.png', title: 'Cheeseburger' },
  { icon: './burrito.png', title: 'Burrito' }, { icon: './butter.png', title: 'Butter' }, { icon: './cake.png', title: 'Cake' },
  { icon: './candy.png', title: 'Candy' }, { icon: './soup.png', title: 'Canned Food / Soup' }, { icon: './carrot.png', title: 'Carrot' },
  { icon: './champagne.png', title: 'Champagne / Sparkling Wine' }, { icon: './cheese.png', title: 'Cheese' }, { icon: './cherries.png', title: 'Cherries' },
  { icon: './nuts.png', title: 'Nuts' }, { icon: './chicken-leg.png', title: 'Chicken / Poultry' }, { icon: './chocolate-bar.png', title: 'Chocolate' },
  { icon: './cocktail.png', title: 'Cocktail / Martini' }, { icon: './coconut.png', title: 'Coconut' },
  { icon: './coffee.png', title: 'Coffee / Hot Drink' }, { icon: './cookie.png', title: 'Cookie' }, { icon: './corn.png', title: 'Corn' },
  { icon: './crab.png', title: 'Crab / Lobster' }, { icon: './croissant.png', title: 'Croissant' }, { icon: './cucumber.png', title: 'Cucumber' },
  { icon: './cupcake.png', title: 'Cupcake / Muffin' }, { icon: './curry.png', title: 'Curry' }, { icon: './skewer.png', title: 'Skewer' },
  { icon: './donut.png', title: 'Donut' }, { icon: './dumpling.png', title: 'Dumplings' }, { icon: './egg.png', title: 'Egg' },
  { icon: './fried-egg.png', title: 'Egg (Fried)' }, { icon: './eggplant.png', title: 'Eggplant' }, { icon: './meatballs.png', title: 'Meatball' },
  { icon: './flatbread.png', title: 'Flatbread / Arepa' }, { icon: './fondue.png', title: 'Fondue / Cheese Dip' },
  { icon: './french-fries.png', title: 'Fries' }, { icon: './garlic.png', title: 'Garlic' },
  { icon: './grape.png', title: 'Grapes' }, { icon: './honey.png', title: 'Honey' },
  { icon: './hot-dog.png', title: 'Hot Dog' }, { icon: './chili.png', title: 'Hot Pepper / Spicy' },
  { icon: './ice-cream-scoop.png', title: 'Ice Cream (Scoop)' }, { icon: './ice-cream-cone.png', title: 'Ice Cream (Cone)' }, { icon: './juice-box.png', title: 'Juice Box' },
  { icon: './kiwi.png', title: 'Kiwi' }, { icon: './lemon.png', title: 'Lemon' }, { icon: './lettuce.png', title: 'Lettuce / Greens' },
  { icon: './lollipop.png', title: 'Lollipop' }, { icon: './mango.png', title: 'Mango' },
  { icon: './milk.png', title: 'Milk' },
  { icon: './mushroom.png', title: 'Mushroom' }, { icon: './ramen.png', title: 'Noodles / Ramen' },
  { icon: './squid.png', title: 'Octopus / Squid' }, { icon: './olive.png', title: 'Olive' },
  { icon: './onion.png', title: 'Onion' }, { icon: './orange.png', title: 'Orange' },
  { icon: './pancakes.png', title: 'Pancakes' }, { icon: './spaghetti.png', title: 'Pasta' }, { icon: './peach.png', title: 'Peach' },
  { icon: './peanut.png', title: 'Peanuts' }, { icon: './pear.png', title: 'Pear' }, { icon: './pea.png', title: 'Peas / Pea Pod' },
  { icon: './pie.png', title: 'Pie' }, { icon: './pineapple.png', title: 'Pineapple' }, { icon: './pita.png', title: 'Pita' },
  { icon: './pizza.png', title: 'Pizza' }, { icon: './popcorn.png', title: 'Popcorn' },
  { icon: './potato.png', title: 'Potato' }, { icon: './pretzel.png', title: 'Pretzel' }, { icon: './pudding.png', title: 'Pudding' },
  { icon: './rice-bowl.png', title: 'Rice' },
  { icon: './salad.png', title: 'Salad' },  { icon: './sausage.png', title: 'Sausage' },
  { icon: './sandwich.png', title: 'Sandwich' }, { icon: './snow-cone.png', title: 'Shaved Ice' }, { icon: './shrimp.png', title: 'Shrimp' },
  { icon: './shrimp-fried.png', title: 'Shrimp (Fried)' }, { icon: './soda.png', title: 'Soda / Fast Food Drink' },
  { icon: './steak.png', title: 'Steak / Meat' }, { icon: './casserole.png', title: 'Stew / Casserole' }, { icon: './strawberry.png', title: 'Strawberry' },
  { icon: './sushi.png', title: 'Sushi' }, { icon: './sweet-potato.png', title: 'Sweet Potato / Yam' }, { icon: './taco.png', title: 'Taco' },
  { icon: './takeout.png', title: 'Takeout Box' }, { icon: './tea.png', title: 'Tea' },
  { icon: './tomato.png', title: 'Tomato' },
  { icon: './pill.png', title: 'Vitamin / Supplement' }, { icon: './waffle.png', title: 'Waffle' }, { icon: './watermelon.png', title: 'Watermelon' },
  { icon: './wine.png', title: 'Wine' },{ icon: './yogurt.png', title: 'Yogurt' },
  { icon: './snack.png', title: 'Snack / Chips' }, { icon: './fish.png', title: 'Fish' }, { icon: './crackers.png', title: 'Crackers' },
  { icon: './guacamole.png', title: 'Guacamole' }, { icon: './bar.png', title: 'Granola Bar' }, { icon: './milk-shake.png', title: 'Milk Shake' },
  { icon: './oats.png', title: 'Oats / Granola' }, { icon: './dipping-sauce.png', title: 'Dipping Sauce' }, { icon: './chicken-nuggets.png', title: 'Chicken Nuggets' },
  { icon: './iced-coffee.png', title: 'Iced Coffee' }, { icon: './quesadilla.png', title: 'Quesadilla' }, { icon: './protein-shake.png', title: 'Protein Shake' },
  { icon: './garlic-bread.png', title: 'Garlic Bread' }, { icon: './peanut-sandwich.png', title: 'Peanut Butter Sandwich' }, { icon: './biscuit.png', title: 'Biscuit' },
  { icon: './sour-cream.png', title: 'Sour Cream / Cream Cheese' }, { icon: './chicken-sandwich.png', title: 'Chicken Sandwich' }, { icon: './hummus.png', title: 'Hummus' },
  { icon: './smoothie.png', title: 'Smoothie' }, { icon: './ice-cream-pint.png', title: 'Ice Cream (Pint)' }, { icon: './churros.png', title: 'Churros' },
  { icon: './sub.png', title: 'Sub' }, { icon: './sugar.png', title: 'Sugar' }, { icon: './can.png', title: 'Soda Can' },
  { icon: './hash-brown.png', title: 'Hash Brown' }, { icon: './meat.png', title: 'Turkey / Chicken' }, { icon: './breakfast-sandwich.png', title: 'Breakfast Sandwich' },
  { icon: './lasagna.png', title: 'Lasagna' }, { icon: './cinnamon-roll.png', title: 'Cinnamon Roll' }, { icon: './macaroni.png', title: 'Macaroni' },
  // Custom Image Examples: Just drop files in the `public` folder and reference them with `./`!
  //{ icon: './scale.png', title: 'Kitchen Scale' }

].sort((a, b) => a.title.localeCompare(b.title));